
import "./globals.css";
import Header from "./sections/Header";
import Footer from "./sections/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between  h-screen">
      <div className="wrapper">
      <Header/>
      {children}
      </div>
      <Footer/>
      </body>
    </html>
  );
}
